description: 'The backend app is the official app to develop, configure and maintain your API.'
screenshot: 'https://www.fusio-project.org/media/apps/backend.png'
website: 'https://github.com/apioo/fusio-apps-backend'
scopes:
  - backend
  - consumer
  - authorization
